# Generated by Django 4.2.6 on 2023-10-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.URLField(default='null'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
