# Generated by Django 4.2.6 on 2023-10-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_car_image_url_delete_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='racetrack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='taxi',
            field=models.BooleanField(default=False),
        ),
    ]
