# Generated by Django 4.2.6 on 2023-11-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_car_events_car_racetrack_car_taxi'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'UserLevel',
                'verbose_name_plural': 'UserLevels',
            },
        ),
    ]
