# Generated by Django 4.2.6 on 2023-11-19 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_userlevel'),
        ('authentication', '0002_user_referral_token_user_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loyalty_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='backend.userlevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='loyalty_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
