# Generated by Django 5.0 on 2023-12-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_changerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
