"Generating YAML":
  image: 
    name: python:3.12.0-bullseye
  stage: .pre
  environment: Production
  before_script:
    - pip install jinja2
  script:
    - python backend/generate_yaml.py
  artifacts:
    paths:
      - backend/app-spec.yaml
    expire_in: 2 minutes
  only:
    - backend



"Deploy to DigitalOcean":
  environment: Production
  image:
    name: digitalocean/doctl:latest
    entrypoint: [""]
  stage: deploy
  script:
    - /app/doctl auth init -t $DO_API_TOKEN
    - /app/doctl apps create-deployment $DO_APP_ID --force-rebuild
    - /app/doctl apps update $DO_APP_ID --spec backend/app-spec.yaml
  only:
    - backend
  dependencies:
    - "Generating YAML"


pages:
  image: ruby:2.7
  script:
    - gem install bundler -v 2.4.22
    - bundle install
    - cd frontend
    - bundle exec jekyll build -d ../public
  artifacts:
    paths:
      - public
  only:
    - frontend
